<PopupLabel@Label>:
	font_size: "25sp"
	text_size: self.size
	valign: "middle"
	halign: "left"
	size_hint_y: 0.2

<EndgamePopup>:
	id: pop2
	auto_dismiss: False
	size_hint: 0.9, 0.8
	title: "Game Over"

	BoxLayout:
		orientation: "vertical"

		Label:
			text: "GAME OVER"
			font_size: "60sp"
			size_hint_y: 0.7


		Button:
			text: "Back to Home"
			font_size: "30sp"
			size_hint_y: 0.3
			on_press: pop2.dismiss()

<ErrorPopup>:
	id: pop4
	auto_dismiss: False
	size_hint: 0.9, 0.8
	title: "Illegal Move Made"

	BoxLayout:
		orientation: "vertical"

		Label:
			id: warning_message
			text: "No"
			font_size: "60sp"
			size_hint_y: 0.7


		Button:
			text: "Back to Game"
			font_size: "30sp"
			size_hint_y: 0.3
			on_press: pop4.dismiss()

<ColorPopup>:
	id: pop3
	auto_dismiss: False
	size_hint: 0.9, 0.8
	title: "Instructions - Colors"

	BoxLayout:
		orientation: "vertical"

		PopupLabel:
			text: "Colors:"		

		GridLayout:
			size_hint_y: 0.4
			cols: 2		
	
			PopupLabel:
				text: "   Green: Legal moves"		

			PopupLabel:
				text: "   Blue: Last move made"

			PopupLabel:
				text: "   Yellow: Illegal Move"		

			PopupLabel:
				text: "   Magenta: Hint or CPU move"		

			PopupLabel:
				text: "   Red: Check"

			PopupLabel:
				text: "   White: Piece lifted"
		
		Label:
			size_hint_y: 0.1

		Button:
			text: "Play"
			font_size: "30sp"
			size_hint_y: 0.3
			on_press: pop3.dismiss()

<SimplePopup>:
	id: pop
	auto_dismiss: False
	size_hint: 0.9, 0.8
	title: "Instructions"

	BoxLayout:
		orientation: "vertical"

		PopupLabel:
			text: "Press 'end turn' at end of turn"

		Label:
			size_hint_y: 0.1

		PopupLabel:
			text: "Place piece on center of square when making move"

		Label:
			size_hint_y: 0.2

		Button:
			text: "Next Page"
			font_size: "30sp"
			size_hint_y: 0.3
			on_press: pop.dismiss_pop()


<PlayGameScreen>:
	id: screen_id_play

	BaseScreen:
	
		StatusBar:
			Label:

			HelpIcon:
			
			SaveIcon:

			SettingIcon:

			QuitIcon:

		ElementBox:
			spacing: 30

			Label:
				id: turn_label
				size_hint_y: 0.3
				text: "Turn: White"
				font_size: "60sp"

			BoxLayout:
				orientation: "horizontal"
				size_hint_y: 0.7
				spacing: 30

				Button:
					text: "Show Good Move"
					font_size: "30sp"
					on_release: root.game_hint()

				Button:
					text: "End Turn"
					font_size: "30sp"
					on_release: root.end_turn()
			
