#:include chessui_homescreen.kv
#:include chessui_startscreen_p1.kv
#:include chessui_startscreen_p2.kv
#:include chessui_boardsetupscreen.kv
#:include chessui_settings.kv
#:include chessui_loadgame.kv
#:include chessui_playgame.kv
#:include chessui_savegame.kv

<BaseScreen@BoxLayout>:
	orientation: "vertical"

<ElementBox@BoxLayout>:
	orientation: "vertical"
	size_hint_y: 0.9
	padding: 50, 20
	
<ButtonImage@Image>
	size_hint: None, None
	width: self.parent.width
	height: self.width
	center_x: self.parent.center_x - (self.parent.width * 0)
	center_y: self.parent.center_y + (self.height * 0.01)

<BackIcon@Button>:
	size_hint_x: None 
	size_hint_y: 1.0
	width: self.height
	on_release: root.parent.parent.parent.manager.current = "home"

	ButtonImage:
		source: "img/back_icon.png"

<HelpIcon>:
	size_hint_x: None 
	size_hint_y: 1.0
	width: self.height
	on_release: root.open_help()

	ButtonImage:
		source: "img/help_icon.png"

<SettingIcon@Button>:
	size_hint_x: None 
	size_hint_y: 1.0
	width: self.height
	on_release: root.parent.parent.parent.manager.current = "settings"
	
	ButtonImage:
		source: "img/setting_icon.png"

<SaveIcon@Button>:
	size_hint_x: None 
	size_hint_y: 1.0
	width: self.height
	on_release: root.parent.parent.parent.manager.current = "save"
	
	ButtonImage:
		source: "img/save_icon.png"

<QuitIcon@Button>:
	size_hint_x: None 
	size_hint_y: 1.0
	width: self.height
	on_release: app.stop()
	
	ButtonImage:
		source: "img/quit_icon.png"


<StatusBar@BoxLayout>:
	orientation: "horizontal"
	size_hint_y: 0.2
	padding: 5
	spacing: 10

	canvas.before:
		Color:
			rgba: 0.0, 0.5, 0.5, 1
		Rectangle:
			pos: self.pos
			size: self.size




		
		


