#:include chessui_homescreen.kv
#:include chessui_startscreen_p1.kv
#:include chessui_startscreen_p2.kv
#:include chessui_boardsetupscreen.kv
#:include chessui_settings.kv
#:include chessui_loadgame.kv
#:include chessui_playgame.kv
#:include chessui_savegame.kv

<BaseScreen@BoxLayout>:
	orientation: "vertical"

<ElementBox@BoxLayout>:
	orientation: "vertical"
	size_hint_y: 0.9
	padding: 50, 20
	
<ButtonImage@Image>
	size_hint: None, None
	width: self.parent.width
	height: self.width
	center_x: self.parent.center_x
	center_y: self.parent.center_y + (self.height * 0.01)

<StatusBar@BoxLayout>:
	orientation: "horizontal"
	size_hint_y: 0.1
	padding: 5
	spacing: 10

	canvas.before:
		Color:
			rgba: 0.0, 0.5, 0.5, 1
		Rectangle:
			pos: self.pos
			size: self.size

	Label:

	Image:
		source: "img/brightness_med_icon.png"
		size_hint_x: None 
		size_hint_y: 1.0
		width: self.height
		keep_ratio: True
	
	Image:
		source: "img/battery_20_icon.png"
		size_hint_x: None 
		size_hint_y: 1.0
		width: self.height
		keep_ratio: True

	Button:
		size_hint_x: None 
		size_hint_y: 1.0
		width: self.height
		on_release: root.parent.parent.manager.current = "save"
	
		ButtonImage:
			source: "img/save_icon.png"

	Button:
		size_hint_x: None 
		size_hint_y: 1.0
		width: self.height
		on_release: root.parent.parent.manager.current = "home"
	
		ButtonImage:
			source: "img/home_icon.png"

	Button:
		size_hint_x: None 
		size_hint_y: 1.0
		width: self.height
		on_release: root.parent.parent.manager.current = "settings"
	
		ButtonImage:
			source: "img/setting_icon.png"
		
	Button:
		size_hint_x: None 
		size_hint_y: 1.0
		width: self.height
		on_release: app.stop()
	
		ButtonImage:
			source: "img/setting_icon.png"
		


