<HomeScreen>:
	id: screen_id_home

	BaseScreen:
	
		StatusBar:

		ElementBox:
			padding: 50, 70
			spacing: 20

			Button:
				text: "Single Player"
				size_hint_y: 0.25
				on_release: root.manager.current = "start_p1"

			Button:
				text: "Multiplayer"
				size_hint_y: 0.25
				on_release: root.manager.current = "start_p2"
			
			Button:
				text: "Load Game"
				size_hint_y: 0.25
				#on_release: app.stop()
				on_release: root.manager.current = "load"
